import socket #socket object will be used to make the connection
#CONSTANTS
HEADER = 124 # wILL BE THE HEADER LENGTH
PORT = 1996  # Port that the socket will be using
FORMAT = 'utf-8' #THIS WILL BE THE ENCODING FORMAT WHEN SENDING HEADER
DISCONNECT_MESSAGE = "!disconnect" #WHEN CLEINT DISCONNECTS OR TERMINATES CONNECTION
SERVER = "192.168.1.26" #NOTE THIS IS LOCAL IP ADDRESS ON LAN, PLEASE ADJUST IT TO THE SERVER IP ADDRESS BY RUNNING IPCONFIG ON WINDOWS
ADDR = (SERVER, PORT) #ADDRESS WILL BE TUPLE OF IP ADDRESS OF SERVER AND PORT#
client = socket.socket(socket.AF_INET, socket.SOCK_STREAM) #CREATE NEW VARIABLE CALLED CLIENT AND MAKE IT AN OBJECT OF THIS CONNECTION
client.connect(ADDR) #CLIENT CONNECTS TO ABOVE IP ADDRESS

